<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNetAI.Application\DotNetAI.Application.csproj" />
    <ProjectReference Include="..\DotNetAI.Infrastructure\DotNetAI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
